#!/bin/bash

for i in $(seq 1 500); do
  uid="usuario$i"
  cn="Usuario $i"
  uidNumber=$((10000 + i))
  gidNumber=10000
  homeDir="/home/$uid"
  password="contraseña$i"  # Genera contraseñas únicas para cada usuario

  cat <<EOF > user$i.ldif
dn: uid=$uid,ou=equipos,dc=techfix,dc=local
objectClass: top
objectClass: posixAccount
objectClass: inetOrgPerson
uid: $uid
cn: $cn
sn: Apellido$i
uidNumber: $uidNumber
gidNumber: $gidNumber
homeDirectory: $homeDir
userPassword: {SSHA}$(slappasswd -s $password)
  EOF

ldapadd -x -D cn=admin,dc=techfix,dc=local -W -f user$i.ldif

done
